### ISSUE TITLE
QGIS 2.10 can't load geogig (possible user error)

### ISSUE THREAD

**Issue by spatialsteve** [boundlessgeo/qgis-geogig-plugin#32]
This is possibly an error on my part but thought I would reach out none the less.

After placing the plugin in the correct directory for plugins I get the following error when starting QGIS.

```
Couldn't load plugin geogig due to an error when calling its classFactory() method 

OSError: [Errno 2] No such file or directory: '/Users/stephendonaldson/.qgis2/python/plugins/geogig/geogig/bin/geogig/bin' 
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 306, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/stephendonaldson/.qgis2/python/plugins/geogig/__init__.py", line 22, in classFactory
    from geogig.plugin import GeoGigPlugin
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/stephendonaldson/.qgis2/python/plugins/geogig/geogig/__init__.py", line 13, in 
    for bin in os.listdir(gg_path):
OSError: [Errno 2] No such file or directory: '/Users/stephendonaldson/.qgis2/python/plugins/geogig/geogig/bin/geogig/bin'


Python version: 2.7.10 (default, Oct 23 2015, 18:05:06) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] 
QGIS version: 2.12.1-Lyon Lyon, exported 

Python Path:
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing
/Users/stephendonaldson/.qgis2/python/plugins/processing_workflow
/Users/stephendonaldson/.qgis2/python/plugins/geogig/ext-libs/keyring-4.0-py2.7.egg
/Users/stephendonaldson/.qgis2/python/plugins/geogig/ext-libs/python_dateutil-1.5-py2.7.egg
/Users/stephendonaldson/.qgis2/python/plugins/geogig/ext-libs/geogig_py-1.1_SNAPSHOT-py2.7.egg
/Users/stephendonaldson/.qgis2/python/plugins/geogig/ext-libs/py4j-0.9-py2.7.egg
/Users/stephendonaldson/.qgis2/python/plugins/geogig/ext-libs/requests-2.7.0-py2.7.egg
/Users/stephendonaldson/.qgis2/python/plugins/GeoCoding/libs
/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/stephendonaldson/.qgis2/python
/Users/stephendonaldson/.qgis2/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/SQLite3.framework/Versions/C/Python/2.7
/Library/Frameworks/GEOS.framework/Versions/3/Python/2.7/site-packages
/Library/Python/2.7/site-packages/numpy-override
/Library/Python/2.7/site-packages/matplotlib-override
/Library/Frameworks/GDAL.framework/Versions/1.11/Python/2.7/site-packages
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC
/Library/Python/2.7/site-packages
/Users/stephendonaldson/.qgis2//python
/Users/stephendonaldson/.qgis2/python/plugins/geogig/ext-libs
/Users/stephendonaldson/.qgis2/python/plugins/mmqgis/forms
/Users/stephendonaldson/.qgis2/python/plugins
.
/Applications/QGIS.app/Contents/Resources/python/plugins/fTools/tools
```

**Comment by abettermap** [comment]
Same here, looks like something incorrect in `__init__.py` file. 

Until it is resolved, you could try the temp fix that seems to be working for me so far: copy _plugins/geogig/bin_ to _plugins/geogig/geogig/bin_.

**Comment by vmontesc** [comment]
Hello,
I have installed the version 2.18.9 and I get the following error when trying to create a repository using the geogig plugin:

_There has been a problem while creating the repository
An unhandled error ocurred: Guice provision errors:

1) Error in custom provider,java.lang.IllegalStateException: No storage provider found
for storage.objects='rocksdb0 and rocksdb.version='1'
while locating org.locationtech.geogig.di.PluginsModule.configure(PluginsModule.java:39)
while locating org.locationtech.geogig.storage.ObjectDatabase

1 error. Se the log for more details._

Any help?

Best regards.
