### ISSUE TITLE
exception when: After add layer => "show changes introduced by this version" 

### ISSUE THREAD

**Issue by luipir** [boundlessgeo/qgis-geogig-plugin#7]
jus added layer bikepbx, then "show changes introduced by this version" genraqte the following exception in console:

Traceback (most recent call last):
  File "/home/ginetto/.qgis2/python/plugins/geogig/gui/dialogs/historyviewer.py", line 103, in <lambda>
    diffAction.triggered.connect(lambda: self.showDiffs(item.commit))
  File "/home/ginetto/.qgis2/python/plugins/geogig/gui/dialogs/historyviewer.py", line 196, in showDiffs
    dlg = DiffViewerDialog(self, self.repo, commita, commitb)
  File "/home/ginetto/.qgis2/python/plugins/geogig/gui/dialogs/diffviewerdialog.py", line 91, in **init**
    self.computeDiffs()
  File "/home/ginetto/.qgis2/python/plugins/geogig/gui/dialogs/diffviewerdialog.py", line 235, in computeDiffs
    self.computeLayerDiffs(self.allchanges.keys()[0])
  File "/home/ginetto/.qgis2/python/plugins/geogig/gui/dialogs/diffviewerdialog.py", line 266, in computeLayerDiffs
    execute(_computeLayerDiff)
  File "/home/ginetto/.qgis2/python/plugins/geogig/gui/executor.py", line 61, in execute
    return func()
  File "/home/ginetto/.qgis2/python/plugins/geogig/gui/dialogs/diffviewerdialog.py", line 244, in _computeLayerDiff
    self.createTableDataFromLayers()
  File "/home/ginetto/.qgis2/python/plugins/geogig/gui/dialogs/diffviewerdialog.py", line 204, in createTableDataFromLayers
    featuredict[GEOMETRY_FIELD][1] = QgsGeometry(feature.geometry())
TypeError: arguments did not match any overloaded call:
  QgsGeometry(): too many arguments
  QgsGeometry(QgsGeometry): argument 1 has unexpected type 'NoneType'

**Comment by volaya** [comment]
So the changes where the first commit of that layer, right?

**Comment by luipir** [comment]
right

but probably could be also records without geometry... I would check

**Comment by alexbruy** [comment]
Seems fixed in master. Please reopen if necessary
